---
title: "Proposal"
header-includes:
  - \usepackage{setspace}
  - \usepackage{xcolor, colortbl}
  - \usepackage{amssymb, amsmath, amsthm}
  - \usepackage{graphicx}
  - \usepackage{natbib}
  - \usepackage{float}
  - \usepackage{graphicx}
  - \usepackage{setspace}
  - \usepackage{algorithm}
  - \usepackage{algorithmic} 
  - \usepackage{epstopdf}
  - \usepackage{bm}
fontsize: 12pt
output: 
  bookdown::pdf_document2:
    toc: False
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
\newcommand{\bc}{\mathbf{c}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\R}{\mathbf{R}}
\newcommand{\bbeta}{\mathbf{\beta}}
\newtheorem{example}{Example}
\doublespacing


Typically, we face the problem of solving 

$$V_0(x_0)=\sup_{\mathbf{c}_0}\mathbf{E}[\sum_{t=0}^{T-1}\delta^{t}u(\mathbf{X}_t,c_t)+U(\mathbf{X}_T)\delta^T]$$
such that $\bc_0=\{c_0,c_1,...c_{T-1}\}$ and the state evolves according to

$$\mathbf{X}_{t+1}=g(\mathbf{X}_t,\mathbf{\varepsilon}_t) \in \mathbf{R}^d$$

^[In most cases, the control also affects the evolution of states. A simple change of variable condition allows us to  ``push-out"  the control of the state evolution.] exogenous shocks $\mathbf\varepsilon_t \in \R^d$.

Rewriting in the Bellman equation format, we have
$$V_t(x)=\sup_{\mathbf{c}_t}u(x,c_t)+\mathbf{E}[V_{t+1}(\mathbf{X}_{t+1})|\mathbf{X}_t=\mathbf{x}_t]$$
with the boundary condition 
$$V_T(x)=U(x).$$
In order to solve this, the dynamic problem start at $T-1$, one needs to solve the optimization problem at each time and iterate the valuation backwards. In simple dynamic program, problems arise when the dimension $d$ is large. At each time, $t$, the $\E_t$ is conditioning  on $\sigma(\mathbf{X}_t)$, one cannot easily derive it analytically, hence making the optimization cumbersome to solve. Numerical approximation schemes, e.g. Monte-Carlo, can be used together with dynamic problem for solving this type of problems, but its numerical performance and theoretical properties are highly dependent on the structure of the problem considered.


Instead, we consider a single index 
$$Y_t=s(\mathbf{X}_t,\mathbf\beta_t) \in \mathbf{R}$$ 
and rewrite the Bellman equation into
\begin{equation}
(\#eq:single-bell)
V_t(y)=\sup_{\bc_t,\bbeta_t}u(y,c_t)+\E[V_{t+1}(Y_{t+1})|Y_t=y] \mbox{ for } \bbeta_t=\{\beta_t,\beta_{t+1},...,\beta_{T}\}
\end{equation}
with the boundary condition
$$V_T(y)=U(y).$$
such that 
$$Y_{t+1}=s(g(\mathbf{X}_t,\varepsilon_t) ,\beta_{t+1}).$$
We have now effectively reduced the d-dimensional problem into one, and know the problem becomes to finding the distribution $F_t(y;\beta_t)$ of $Y_t$ in order to evaluate the integral. Our idea is to use the empirical distribution $F^n_t(y; \beta_t)$.

Suppose given this empirical distribution, the optimal controls in equation \@ref(eq:single-bell) can be solved exactly.  We would like to analysis the convergence behaviour of the resulting $V_0(x_0)^n$ to the true $V_0(x_0)$. 


__Problem to Solve__  

* Conditions for the validity of equation \@ref(eq:single-bell)
* Given $F^n_t$, can we evaluate $\E_t$.


\begin{example}[Portfolio Choice and Optimal Consumption Decision]
Consider a portfolio choice when a large number of assets are considered with a constraint that the sum of all the weights is equal to one and a weight could be allowed to be negative. In combination with the portfolio choice, we solve optimal consumption and investment decision under stochastic dynamical programming.
\end{example} 
Suppose that there are $q$ number of assets considered for the construction of a target portfolio and their returns and the associated covariance matrix are denoted as $\mathbf{R}=(R_1,R_2,...,R_q)'$. Let the return of the target portfolio be $R_{p}=\mathbf{w}'\mathbf{R}$ and hence $R_{p}$ does not belong to the vector $\mathbf{R}$. Let the return of the target portfolio be $\mu_p$. Under this setup, we can consider the following regression model:

$$\begin{aligned}
\mu_p & =\mathbb{E}[w_{1}R_{1t}+w_{2}R_{2t}+...+w_{q}R_{qt}]\nonumber\\
& =\mathbb{E}[(1-\sum_{i=2}^{q}w_{i})R_{1t}+w_{2}R_{2t}...+w_{q}R_{qt}]\nonumber\\
\end{aligned}$$

\begin{equation}
(\#eq:port-index)
R_{1t}  =\mu_p+\sum_{i=2}^{q}w_{i}X_{it}+\epsilon_t 
\end{equation}


where $X_{it}=R_{1t}-R_{it}$.
Under our general setup, $Y_t=\hat{\mathbf{w}}'\mathbf{R}_t$ where $\hat{\mathbf{w}}$ is a OLS estimator for $\mathbf{w}$ in \@ref(eq:port-index). 


$$V_0(x_0)=\sup_{\mathbf{c}_0, \mathbf{\beta}_0}\mathbf{E}[u(C_0(W_0, c_0))+\sum_{j=1}^{T-1}u(C_j({W}_j(\mathbf\beta_{j-1}, \mathbf{R}_{j-1}, \mathbf\omega_{j-1}, r_f),c_j))\delta^{j} + u(W_T(\mathbf\beta_{T-1}, \mathbf{R}_{T-1}, \mathbf\omega_{T-1}, r_f))\delta^T]$$

contional on the boundary condition 

$$V_T(x_T)=\sup_{\mathbf{\beta}_{T-1}}\mathbf{E}[ u(W_T(\mathbf\beta_{T-1}, \mathbf{r}_{T-1}, \mathbf\omega_{T-1}, r_f))]$$

where

* $\mathbf{R}_t$ is a vector of returns of different risky assets at time $t$.
* $\mathbf\omega_t$ is a vector of weight of different assets in risky portfolio.
* $\beta_t$ is the weight allocated to the risky portfolio comparing to risk free asset
* $W_t$ is the wealth at time $t$, a function of return $\mathbf{r}_{t-1}$ and weight $\mathbf\beta_{t-1}$ which are observed or determined from the last period.
* $c_t$ is the a vector of 2 control variables which in turn determines consumption $C_t$.
* $u$ is the utility function depending on consumption or the terminal wealth.

The state of $W_t$ evolves according to 

$$Y_t=\hat{\mathbf{w}}'\mathbf{R}_t$$

$$\begin{aligned}W_{t+1}&=(W_t-C_t)(\mathbf{\beta}_t\cdot {Y}_t+(1-\beta_t)\cdot r_f+1)\\ C_t&=W_t\cdot \frac{\exp\{c_{1, t}+c_{2,t}W_{t}\}}{1+\exp\{c_{1, t}+c_{2,t}W_{t}\}}\end{aligned}$$

where we assume the comsumption is propotional to wealth and the propotion is calculated by applying inverse logit function.  

<!-- The utility function is assumed to be $u(x)=\frac{x^{1-\lambda}}{1-\lambda}$. -->
The utility function is assumed to be $u(x)=\log{x}$.

If we write it into Bellman equation 



$$V_t(x_t)=\sup_{\mathbf{c}_t, \mathbf{\beta}_t}\mathbf{E}[\sum_{j=t}^{T-1}u(C_j({W}_j(\mathbf\beta_{j-1}, \mathbf{r}_{j-1}, \mathbf{\omega}_{j-1}, r_f),c_j))\delta^{j-t} + u(W_T(\mathbf\beta_{T-1}, \mathbf{r}_{T-1}, \mathbf{\omega}_{T-1}, r_f))\delta^{T-t}]$$

This example is a typical high-dimensional optimization problem which cannot be sloved under the current literature, especially when the number of assets to be chosen is quite big. Therefore, we take a novel two steps approach where we first compute the weights using lasso and then using dynamic programming to calculate the appropriate control variable $c_t$.

