# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optim_for_each_cpp <- function(x, f, max_iteration, paralist) {
    .Call(`_stocon_optim_for_each_cpp`, x, f, max_iteration, paralist)
}

